package com.lsurvila.callmonitortask.model

enum class CallMonitorState {
    NOT_STARTED,
    STARTING,
    PHONE_NOT_AVAILABLE,
    PHONE_PERMISSION_NEEDED,
    PHONE_PERMISSION_DENIED,
    CONTACTS_PERMISSION_NEEDED,
    CONTACTS_PERMISSION_DENIED,
    WIFI_DISCONNECTED,
    STARTED,
    STOPPING,
    STOPPED
}